name: Generate postman collection and update if changed

on:
  schedule:
    # Runs every 30th day at midnight
    - cron: '0 0 */30 * *'

jobs:

  generate-collection:
    runs-on: ubuntu-latest

    steps:

    - name: checkout repo
      uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.9.x'

    - name: get graphman
      uses: actions/checkout@v3
      with:
        repository: Escape-Technologies/graphman
        path: graphman

    - name: set up deno
      uses: denoland/setup-deno@v1

    - name: run the graphman command
      run: deno run --allow-net --allow-read --allow-write graphman/src/cli.ts https://api.getmontecarlo.com/graphql --H="x-mcd-id:${{ secrets.MCD_ID }}" -H="x-mcd-token:${{ secrets.MCD_TOKEN }}" --out=new.json

    - name: cleanup graphman
      run: rm -rf graphman/

    - name: check for changes and update repo
      run: python script/main.py

    - name: create branch and add files
      run: |
        git checkout -b update
        git add .
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "added updated collection file"

    - name: push branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: update

    - name: Create pull request
      uses: devops-infra/action-pull-request@v0.5.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        title: Automatic pull request
        target_branch: main
        source_branch: update

