name: Update Collection in SA workspace

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Why are you running manually?'
        default: 'just cuz'

jobs:

  generate-collection:
    runs-on: ubuntu-latest

    steps:

    - name: checkout repo
      uses: actions/checkout@v3

    - name: get postmanctl
      uses: actions/checkout@v3
      with:
       repository: kevinswiber/postmanctl
       path: postmanctl
       
    - name: Setup Go environment 
      uses: actions/setup-go@v4.0.1
      
#     - name: view dir
#       run: ls -l && pwd
      
    - name: installing go dependencies 
      run:  cd postmanctl/cmd/postmanctl && go install 
      
#     - name: debug
#       run: cd postmanctl/cmd/postmanctl && cat ../../../mc_postman_collection.json
    - name: write config yaml
      run: cd postmanctl/cmd/postmanctl && echo ${{ secrets.POSTMANSECRET }} > config.yml
    
    - name: configure
      run: cd postmanctl/cmd/postmanctl && go run main.go config --config config.yml
    
    - name: enter directory postmanctl && replace collection
      run: cd postmanctl/cmd/postmanctl && go run main.go replace collection 24800539-c205410a-d342-41ab-9f06-7ae7b639a0d2 -f  ../../../mc_postman_collection.json
      
 


   
      
